package(default_visibility = ["//visibility:public"])

py_library(
    name = "grpc_health",
    srcs = ["health.py",],
    deps = [
        "//protos/health:health_py_proto",
    ],
    imports=["../../",],
)
